//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ProyectoMovil.com.somee.proyectomovil22 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback IngresarOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback modificarProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback cargarDatosProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarCategoriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizarCategoriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarCategoriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback cargarDatosCategoriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarProveedorOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizarProveedorOperationCompleted;
        
        private System.Threading.SendOrPostCallback cargarDatosProveedorOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarProveedorOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarVentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarventaOperationCompleted;
        
        private System.Threading.SendOrPostCallback verVentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AumentarProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback RestarProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarCompraOperationCompleted;
        
        private System.Threading.SendOrPostCallback verCompraOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarCompraOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistrarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback cargarDatosUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistrarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback modificarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback cargarDatosClienteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = "http://www.proyectomovil22.somee.com/WebService1.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event IngresarCompletedEventHandler IngresarCompleted;
        
        /// <remarks/>
        public event registrarProductoCompletedEventHandler registrarProductoCompleted;
        
        /// <remarks/>
        public event modificarProductoCompletedEventHandler modificarProductoCompleted;
        
        /// <remarks/>
        public event cargarDatosProductoCompletedEventHandler cargarDatosProductoCompleted;
        
        /// <remarks/>
        public event eliminarProductoCompletedEventHandler eliminarProductoCompleted;
        
        /// <remarks/>
        public event registrarCategoriaCompletedEventHandler registrarCategoriaCompleted;
        
        /// <remarks/>
        public event actualizarCategoriaCompletedEventHandler actualizarCategoriaCompleted;
        
        /// <remarks/>
        public event eliminarCategoriaCompletedEventHandler eliminarCategoriaCompleted;
        
        /// <remarks/>
        public event cargarDatosCategoriaCompletedEventHandler cargarDatosCategoriaCompleted;
        
        /// <remarks/>
        public event registrarProveedorCompletedEventHandler registrarProveedorCompleted;
        
        /// <remarks/>
        public event actualizarProveedorCompletedEventHandler actualizarProveedorCompleted;
        
        /// <remarks/>
        public event cargarDatosProveedorCompletedEventHandler cargarDatosProveedorCompleted;
        
        /// <remarks/>
        public event eliminarProveedorCompletedEventHandler eliminarProveedorCompleted;
        
        /// <remarks/>
        public event registrarVentaCompletedEventHandler registrarVentaCompleted;
        
        /// <remarks/>
        public event eliminarventaCompletedEventHandler eliminarventaCompleted;
        
        /// <remarks/>
        public event verVentaCompletedEventHandler verVentaCompleted;
        
        /// <remarks/>
        public event AumentarProductoCompletedEventHandler AumentarProductoCompleted;
        
        /// <remarks/>
        public event RestarProductoCompletedEventHandler RestarProductoCompleted;
        
        /// <remarks/>
        public event registrarCompraCompletedEventHandler registrarCompraCompleted;
        
        /// <remarks/>
        public event verCompraCompletedEventHandler verCompraCompleted;
        
        /// <remarks/>
        public event eliminarCompraCompletedEventHandler eliminarCompraCompleted;
        
        /// <remarks/>
        public event RegistrarUsuarioCompletedEventHandler RegistrarUsuarioCompleted;
        
        /// <remarks/>
        public event actualizarClienteCompletedEventHandler actualizarClienteCompleted;
        
        /// <remarks/>
        public event eliminarUsuarioCompletedEventHandler eliminarUsuarioCompleted;
        
        /// <remarks/>
        public event cargarDatosUsuarioCompletedEventHandler cargarDatosUsuarioCompleted;
        
        /// <remarks/>
        public event RegistrarClienteCompletedEventHandler RegistrarClienteCompleted;
        
        /// <remarks/>
        public event modificarClienteCompletedEventHandler modificarClienteCompleted;
        
        /// <remarks/>
        public event eliminarClienteCompletedEventHandler eliminarClienteCompleted;
        
        /// <remarks/>
        public event cargarDatosClienteCompletedEventHandler cargarDatosClienteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Ingresar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Ingresar(string user, string pwd) {
            object[] results = this.Invoke("Ingresar", new object[] {
                        user,
                        pwd});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void IngresarAsync(string user, string pwd) {
            this.IngresarAsync(user, pwd, null);
        }
        
        /// <remarks/>
        public void IngresarAsync(string user, string pwd, object userState) {
            if ((this.IngresarOperationCompleted == null)) {
                this.IngresarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIngresarOperationCompleted);
            }
            this.InvokeAsync("Ingresar", new object[] {
                        user,
                        pwd}, this.IngresarOperationCompleted, userState);
        }
        
        private void OnIngresarOperationCompleted(object arg) {
            if ((this.IngresarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IngresarCompleted(this, new IngresarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/registrarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void registrarProducto(string codigo, string nombre, string descripcion, string fechaelab, string fechaexp, string cantidad) {
            this.Invoke("registrarProducto", new object[] {
                        codigo,
                        nombre,
                        descripcion,
                        fechaelab,
                        fechaexp,
                        cantidad});
        }
        
        /// <remarks/>
        public void registrarProductoAsync(string codigo, string nombre, string descripcion, string fechaelab, string fechaexp, string cantidad) {
            this.registrarProductoAsync(codigo, nombre, descripcion, fechaelab, fechaexp, cantidad, null);
        }
        
        /// <remarks/>
        public void registrarProductoAsync(string codigo, string nombre, string descripcion, string fechaelab, string fechaexp, string cantidad, object userState) {
            if ((this.registrarProductoOperationCompleted == null)) {
                this.registrarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarProductoOperationCompleted);
            }
            this.InvokeAsync("registrarProducto", new object[] {
                        codigo,
                        nombre,
                        descripcion,
                        fechaelab,
                        fechaexp,
                        cantidad}, this.registrarProductoOperationCompleted, userState);
        }
        
        private void OnregistrarProductoOperationCompleted(object arg) {
            if ((this.registrarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarProductoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/modificarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void modificarProducto(string codigo, string nombre, string descripcion, string fechaelab, string fechaexp, string cantidad, int id) {
            this.Invoke("modificarProducto", new object[] {
                        codigo,
                        nombre,
                        descripcion,
                        fechaelab,
                        fechaexp,
                        cantidad,
                        id});
        }
        
        /// <remarks/>
        public void modificarProductoAsync(string codigo, string nombre, string descripcion, string fechaelab, string fechaexp, string cantidad, int id) {
            this.modificarProductoAsync(codigo, nombre, descripcion, fechaelab, fechaexp, cantidad, id, null);
        }
        
        /// <remarks/>
        public void modificarProductoAsync(string codigo, string nombre, string descripcion, string fechaelab, string fechaexp, string cantidad, int id, object userState) {
            if ((this.modificarProductoOperationCompleted == null)) {
                this.modificarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmodificarProductoOperationCompleted);
            }
            this.InvokeAsync("modificarProducto", new object[] {
                        codigo,
                        nombre,
                        descripcion,
                        fechaelab,
                        fechaexp,
                        cantidad,
                        id}, this.modificarProductoOperationCompleted, userState);
        }
        
        private void OnmodificarProductoOperationCompleted(object arg) {
            if ((this.modificarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.modificarProductoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cargarDatosProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet cargarDatosProducto(string id) {
            object[] results = this.Invoke("cargarDatosProducto", new object[] {
                        id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void cargarDatosProductoAsync(string id) {
            this.cargarDatosProductoAsync(id, null);
        }
        
        /// <remarks/>
        public void cargarDatosProductoAsync(string id, object userState) {
            if ((this.cargarDatosProductoOperationCompleted == null)) {
                this.cargarDatosProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncargarDatosProductoOperationCompleted);
            }
            this.InvokeAsync("cargarDatosProducto", new object[] {
                        id}, this.cargarDatosProductoOperationCompleted, userState);
        }
        
        private void OncargarDatosProductoOperationCompleted(object arg) {
            if ((this.cargarDatosProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cargarDatosProductoCompleted(this, new cargarDatosProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void eliminarProducto(int id) {
            this.Invoke("eliminarProducto", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void eliminarProductoAsync(int id) {
            this.eliminarProductoAsync(id, null);
        }
        
        /// <remarks/>
        public void eliminarProductoAsync(int id, object userState) {
            if ((this.eliminarProductoOperationCompleted == null)) {
                this.eliminarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarProductoOperationCompleted);
            }
            this.InvokeAsync("eliminarProducto", new object[] {
                        id}, this.eliminarProductoOperationCompleted, userState);
        }
        
        private void OneliminarProductoOperationCompleted(object arg) {
            if ((this.eliminarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarProductoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/registrarCategoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void registrarCategoria(string tipo, string descripcion) {
            this.Invoke("registrarCategoria", new object[] {
                        tipo,
                        descripcion});
        }
        
        /// <remarks/>
        public void registrarCategoriaAsync(string tipo, string descripcion) {
            this.registrarCategoriaAsync(tipo, descripcion, null);
        }
        
        /// <remarks/>
        public void registrarCategoriaAsync(string tipo, string descripcion, object userState) {
            if ((this.registrarCategoriaOperationCompleted == null)) {
                this.registrarCategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarCategoriaOperationCompleted);
            }
            this.InvokeAsync("registrarCategoria", new object[] {
                        tipo,
                        descripcion}, this.registrarCategoriaOperationCompleted, userState);
        }
        
        private void OnregistrarCategoriaOperationCompleted(object arg) {
            if ((this.registrarCategoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarCategoriaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/actualizarCategoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void actualizarCategoria(string tipo, string descripcion, int id) {
            this.Invoke("actualizarCategoria", new object[] {
                        tipo,
                        descripcion,
                        id});
        }
        
        /// <remarks/>
        public void actualizarCategoriaAsync(string tipo, string descripcion, int id) {
            this.actualizarCategoriaAsync(tipo, descripcion, id, null);
        }
        
        /// <remarks/>
        public void actualizarCategoriaAsync(string tipo, string descripcion, int id, object userState) {
            if ((this.actualizarCategoriaOperationCompleted == null)) {
                this.actualizarCategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarCategoriaOperationCompleted);
            }
            this.InvokeAsync("actualizarCategoria", new object[] {
                        tipo,
                        descripcion,
                        id}, this.actualizarCategoriaOperationCompleted, userState);
        }
        
        private void OnactualizarCategoriaOperationCompleted(object arg) {
            if ((this.actualizarCategoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizarCategoriaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarCategoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void eliminarCategoria(int id) {
            this.Invoke("eliminarCategoria", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void eliminarCategoriaAsync(int id) {
            this.eliminarCategoriaAsync(id, null);
        }
        
        /// <remarks/>
        public void eliminarCategoriaAsync(int id, object userState) {
            if ((this.eliminarCategoriaOperationCompleted == null)) {
                this.eliminarCategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarCategoriaOperationCompleted);
            }
            this.InvokeAsync("eliminarCategoria", new object[] {
                        id}, this.eliminarCategoriaOperationCompleted, userState);
        }
        
        private void OneliminarCategoriaOperationCompleted(object arg) {
            if ((this.eliminarCategoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarCategoriaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cargarDatosCategoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet cargarDatosCategoria(string id) {
            object[] results = this.Invoke("cargarDatosCategoria", new object[] {
                        id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void cargarDatosCategoriaAsync(string id) {
            this.cargarDatosCategoriaAsync(id, null);
        }
        
        /// <remarks/>
        public void cargarDatosCategoriaAsync(string id, object userState) {
            if ((this.cargarDatosCategoriaOperationCompleted == null)) {
                this.cargarDatosCategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OncargarDatosCategoriaOperationCompleted);
            }
            this.InvokeAsync("cargarDatosCategoria", new object[] {
                        id}, this.cargarDatosCategoriaOperationCompleted, userState);
        }
        
        private void OncargarDatosCategoriaOperationCompleted(object arg) {
            if ((this.cargarDatosCategoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cargarDatosCategoriaCompleted(this, new cargarDatosCategoriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/registrarProveedor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void registrarProveedor(string nombre, string ruc, string direccion, string telefono, string correo) {
            this.Invoke("registrarProveedor", new object[] {
                        nombre,
                        ruc,
                        direccion,
                        telefono,
                        correo});
        }
        
        /// <remarks/>
        public void registrarProveedorAsync(string nombre, string ruc, string direccion, string telefono, string correo) {
            this.registrarProveedorAsync(nombre, ruc, direccion, telefono, correo, null);
        }
        
        /// <remarks/>
        public void registrarProveedorAsync(string nombre, string ruc, string direccion, string telefono, string correo, object userState) {
            if ((this.registrarProveedorOperationCompleted == null)) {
                this.registrarProveedorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarProveedorOperationCompleted);
            }
            this.InvokeAsync("registrarProveedor", new object[] {
                        nombre,
                        ruc,
                        direccion,
                        telefono,
                        correo}, this.registrarProveedorOperationCompleted, userState);
        }
        
        private void OnregistrarProveedorOperationCompleted(object arg) {
            if ((this.registrarProveedorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarProveedorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/actualizarProveedor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void actualizarProveedor(string nombre, string ruc, string direccion, string telefono, string correo, int id) {
            this.Invoke("actualizarProveedor", new object[] {
                        nombre,
                        ruc,
                        direccion,
                        telefono,
                        correo,
                        id});
        }
        
        /// <remarks/>
        public void actualizarProveedorAsync(string nombre, string ruc, string direccion, string telefono, string correo, int id) {
            this.actualizarProveedorAsync(nombre, ruc, direccion, telefono, correo, id, null);
        }
        
        /// <remarks/>
        public void actualizarProveedorAsync(string nombre, string ruc, string direccion, string telefono, string correo, int id, object userState) {
            if ((this.actualizarProveedorOperationCompleted == null)) {
                this.actualizarProveedorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarProveedorOperationCompleted);
            }
            this.InvokeAsync("actualizarProveedor", new object[] {
                        nombre,
                        ruc,
                        direccion,
                        telefono,
                        correo,
                        id}, this.actualizarProveedorOperationCompleted, userState);
        }
        
        private void OnactualizarProveedorOperationCompleted(object arg) {
            if ((this.actualizarProveedorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizarProveedorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cargarDatosProveedor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet cargarDatosProveedor(string ruc) {
            object[] results = this.Invoke("cargarDatosProveedor", new object[] {
                        ruc});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void cargarDatosProveedorAsync(string ruc) {
            this.cargarDatosProveedorAsync(ruc, null);
        }
        
        /// <remarks/>
        public void cargarDatosProveedorAsync(string ruc, object userState) {
            if ((this.cargarDatosProveedorOperationCompleted == null)) {
                this.cargarDatosProveedorOperationCompleted = new System.Threading.SendOrPostCallback(this.OncargarDatosProveedorOperationCompleted);
            }
            this.InvokeAsync("cargarDatosProveedor", new object[] {
                        ruc}, this.cargarDatosProveedorOperationCompleted, userState);
        }
        
        private void OncargarDatosProveedorOperationCompleted(object arg) {
            if ((this.cargarDatosProveedorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cargarDatosProveedorCompleted(this, new cargarDatosProveedorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarProveedor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void eliminarProveedor(int id) {
            this.Invoke("eliminarProveedor", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void eliminarProveedorAsync(int id) {
            this.eliminarProveedorAsync(id, null);
        }
        
        /// <remarks/>
        public void eliminarProveedorAsync(int id, object userState) {
            if ((this.eliminarProveedorOperationCompleted == null)) {
                this.eliminarProveedorOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarProveedorOperationCompleted);
            }
            this.InvokeAsync("eliminarProveedor", new object[] {
                        id}, this.eliminarProveedorOperationCompleted, userState);
        }
        
        private void OneliminarProveedorOperationCompleted(object arg) {
            if ((this.eliminarProveedorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarProveedorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/registrarVenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void registrarVenta(string idproducto, string idcliente, string vntcodigo, int vntcantidad, double vntcostoventa, string vntfecha) {
            this.Invoke("registrarVenta", new object[] {
                        idproducto,
                        idcliente,
                        vntcodigo,
                        vntcantidad,
                        vntcostoventa,
                        vntfecha});
        }
        
        /// <remarks/>
        public void registrarVentaAsync(string idproducto, string idcliente, string vntcodigo, int vntcantidad, double vntcostoventa, string vntfecha) {
            this.registrarVentaAsync(idproducto, idcliente, vntcodigo, vntcantidad, vntcostoventa, vntfecha, null);
        }
        
        /// <remarks/>
        public void registrarVentaAsync(string idproducto, string idcliente, string vntcodigo, int vntcantidad, double vntcostoventa, string vntfecha, object userState) {
            if ((this.registrarVentaOperationCompleted == null)) {
                this.registrarVentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarVentaOperationCompleted);
            }
            this.InvokeAsync("registrarVenta", new object[] {
                        idproducto,
                        idcliente,
                        vntcodigo,
                        vntcantidad,
                        vntcostoventa,
                        vntfecha}, this.registrarVentaOperationCompleted, userState);
        }
        
        private void OnregistrarVentaOperationCompleted(object arg) {
            if ((this.registrarVentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarVentaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarventa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void eliminarventa(int id) {
            this.Invoke("eliminarventa", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void eliminarventaAsync(int id) {
            this.eliminarventaAsync(id, null);
        }
        
        /// <remarks/>
        public void eliminarventaAsync(int id, object userState) {
            if ((this.eliminarventaOperationCompleted == null)) {
                this.eliminarventaOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarventaOperationCompleted);
            }
            this.InvokeAsync("eliminarventa", new object[] {
                        id}, this.eliminarventaOperationCompleted, userState);
        }
        
        private void OneliminarventaOperationCompleted(object arg) {
            if ((this.eliminarventaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarventaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/verVenta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet verVenta(int id) {
            object[] results = this.Invoke("verVenta", new object[] {
                        id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void verVentaAsync(int id) {
            this.verVentaAsync(id, null);
        }
        
        /// <remarks/>
        public void verVentaAsync(int id, object userState) {
            if ((this.verVentaOperationCompleted == null)) {
                this.verVentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverVentaOperationCompleted);
            }
            this.InvokeAsync("verVenta", new object[] {
                        id}, this.verVentaOperationCompleted, userState);
        }
        
        private void OnverVentaOperationCompleted(object arg) {
            if ((this.verVentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verVentaCompleted(this, new verVentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AumentarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AumentarProducto(int cant, int id) {
            this.Invoke("AumentarProducto", new object[] {
                        cant,
                        id});
        }
        
        /// <remarks/>
        public void AumentarProductoAsync(int cant, int id) {
            this.AumentarProductoAsync(cant, id, null);
        }
        
        /// <remarks/>
        public void AumentarProductoAsync(int cant, int id, object userState) {
            if ((this.AumentarProductoOperationCompleted == null)) {
                this.AumentarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAumentarProductoOperationCompleted);
            }
            this.InvokeAsync("AumentarProducto", new object[] {
                        cant,
                        id}, this.AumentarProductoOperationCompleted, userState);
        }
        
        private void OnAumentarProductoOperationCompleted(object arg) {
            if ((this.AumentarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AumentarProductoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RestarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RestarProducto(int cant, int id) {
            this.Invoke("RestarProducto", new object[] {
                        cant,
                        id});
        }
        
        /// <remarks/>
        public void RestarProductoAsync(int cant, int id) {
            this.RestarProductoAsync(cant, id, null);
        }
        
        /// <remarks/>
        public void RestarProductoAsync(int cant, int id, object userState) {
            if ((this.RestarProductoOperationCompleted == null)) {
                this.RestarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRestarProductoOperationCompleted);
            }
            this.InvokeAsync("RestarProducto", new object[] {
                        cant,
                        id}, this.RestarProductoOperationCompleted, userState);
        }
        
        private void OnRestarProductoOperationCompleted(object arg) {
            if ((this.RestarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RestarProductoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/registrarCompra", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void registrarCompra(string idproveedor, string idproducto, string comcodigo, int comcantidad, double comcostocompra, string comfecha) {
            this.Invoke("registrarCompra", new object[] {
                        idproveedor,
                        idproducto,
                        comcodigo,
                        comcantidad,
                        comcostocompra,
                        comfecha});
        }
        
        /// <remarks/>
        public void registrarCompraAsync(string idproveedor, string idproducto, string comcodigo, int comcantidad, double comcostocompra, string comfecha) {
            this.registrarCompraAsync(idproveedor, idproducto, comcodigo, comcantidad, comcostocompra, comfecha, null);
        }
        
        /// <remarks/>
        public void registrarCompraAsync(string idproveedor, string idproducto, string comcodigo, int comcantidad, double comcostocompra, string comfecha, object userState) {
            if ((this.registrarCompraOperationCompleted == null)) {
                this.registrarCompraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarCompraOperationCompleted);
            }
            this.InvokeAsync("registrarCompra", new object[] {
                        idproveedor,
                        idproducto,
                        comcodigo,
                        comcantidad,
                        comcostocompra,
                        comfecha}, this.registrarCompraOperationCompleted, userState);
        }
        
        private void OnregistrarCompraOperationCompleted(object arg) {
            if ((this.registrarCompraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarCompraCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/verCompra", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet verCompra(int id) {
            object[] results = this.Invoke("verCompra", new object[] {
                        id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void verCompraAsync(int id) {
            this.verCompraAsync(id, null);
        }
        
        /// <remarks/>
        public void verCompraAsync(int id, object userState) {
            if ((this.verCompraOperationCompleted == null)) {
                this.verCompraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverCompraOperationCompleted);
            }
            this.InvokeAsync("verCompra", new object[] {
                        id}, this.verCompraOperationCompleted, userState);
        }
        
        private void OnverCompraOperationCompleted(object arg) {
            if ((this.verCompraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verCompraCompleted(this, new verCompraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarCompra", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void eliminarCompra(int id) {
            this.Invoke("eliminarCompra", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void eliminarCompraAsync(int id) {
            this.eliminarCompraAsync(id, null);
        }
        
        /// <remarks/>
        public void eliminarCompraAsync(int id, object userState) {
            if ((this.eliminarCompraOperationCompleted == null)) {
                this.eliminarCompraOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarCompraOperationCompleted);
            }
            this.InvokeAsync("eliminarCompra", new object[] {
                        id}, this.eliminarCompraOperationCompleted, userState);
        }
        
        private void OneliminarCompraOperationCompleted(object arg) {
            if ((this.eliminarCompraCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarCompraCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RegistrarUsuario(string nombre, string apellido, string cedula, string correo, string clave, char rol) {
            this.Invoke("RegistrarUsuario", new object[] {
                        nombre,
                        apellido,
                        cedula,
                        correo,
                        clave,
                        rol});
        }
        
        /// <remarks/>
        public void RegistrarUsuarioAsync(string nombre, string apellido, string cedula, string correo, string clave, char rol) {
            this.RegistrarUsuarioAsync(nombre, apellido, cedula, correo, clave, rol, null);
        }
        
        /// <remarks/>
        public void RegistrarUsuarioAsync(string nombre, string apellido, string cedula, string correo, string clave, char rol, object userState) {
            if ((this.RegistrarUsuarioOperationCompleted == null)) {
                this.RegistrarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarUsuarioOperationCompleted);
            }
            this.InvokeAsync("RegistrarUsuario", new object[] {
                        nombre,
                        apellido,
                        cedula,
                        correo,
                        clave,
                        rol}, this.RegistrarUsuarioOperationCompleted, userState);
        }
        
        private void OnRegistrarUsuarioOperationCompleted(object arg) {
            if ((this.RegistrarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/actualizarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void actualizarCliente(string nombre, string apellido, string cedula, string correo, string clave, char rol, int id) {
            this.Invoke("actualizarCliente", new object[] {
                        nombre,
                        apellido,
                        cedula,
                        correo,
                        clave,
                        rol,
                        id});
        }
        
        /// <remarks/>
        public void actualizarClienteAsync(string nombre, string apellido, string cedula, string correo, string clave, char rol, int id) {
            this.actualizarClienteAsync(nombre, apellido, cedula, correo, clave, rol, id, null);
        }
        
        /// <remarks/>
        public void actualizarClienteAsync(string nombre, string apellido, string cedula, string correo, string clave, char rol, int id, object userState) {
            if ((this.actualizarClienteOperationCompleted == null)) {
                this.actualizarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarClienteOperationCompleted);
            }
            this.InvokeAsync("actualizarCliente", new object[] {
                        nombre,
                        apellido,
                        cedula,
                        correo,
                        clave,
                        rol,
                        id}, this.actualizarClienteOperationCompleted, userState);
        }
        
        private void OnactualizarClienteOperationCompleted(object arg) {
            if ((this.actualizarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizarClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void eliminarUsuario(int id) {
            this.Invoke("eliminarUsuario", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void eliminarUsuarioAsync(int id) {
            this.eliminarUsuarioAsync(id, null);
        }
        
        /// <remarks/>
        public void eliminarUsuarioAsync(int id, object userState) {
            if ((this.eliminarUsuarioOperationCompleted == null)) {
                this.eliminarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarUsuarioOperationCompleted);
            }
            this.InvokeAsync("eliminarUsuario", new object[] {
                        id}, this.eliminarUsuarioOperationCompleted, userState);
        }
        
        private void OneliminarUsuarioOperationCompleted(object arg) {
            if ((this.eliminarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cargarDatosUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet cargarDatosUsuario(string ci) {
            object[] results = this.Invoke("cargarDatosUsuario", new object[] {
                        ci});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void cargarDatosUsuarioAsync(string ci) {
            this.cargarDatosUsuarioAsync(ci, null);
        }
        
        /// <remarks/>
        public void cargarDatosUsuarioAsync(string ci, object userState) {
            if ((this.cargarDatosUsuarioOperationCompleted == null)) {
                this.cargarDatosUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OncargarDatosUsuarioOperationCompleted);
            }
            this.InvokeAsync("cargarDatosUsuario", new object[] {
                        ci}, this.cargarDatosUsuarioOperationCompleted, userState);
        }
        
        private void OncargarDatosUsuarioOperationCompleted(object arg) {
            if ((this.cargarDatosUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cargarDatosUsuarioCompleted(this, new cargarDatosUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void RegistrarCliente(string nombre, string apellido, string cedula, string direccion, string telefono) {
            this.Invoke("RegistrarCliente", new object[] {
                        nombre,
                        apellido,
                        cedula,
                        direccion,
                        telefono});
        }
        
        /// <remarks/>
        public void RegistrarClienteAsync(string nombre, string apellido, string cedula, string direccion, string telefono) {
            this.RegistrarClienteAsync(nombre, apellido, cedula, direccion, telefono, null);
        }
        
        /// <remarks/>
        public void RegistrarClienteAsync(string nombre, string apellido, string cedula, string direccion, string telefono, object userState) {
            if ((this.RegistrarClienteOperationCompleted == null)) {
                this.RegistrarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarClienteOperationCompleted);
            }
            this.InvokeAsync("RegistrarCliente", new object[] {
                        nombre,
                        apellido,
                        cedula,
                        direccion,
                        telefono}, this.RegistrarClienteOperationCompleted, userState);
        }
        
        private void OnRegistrarClienteOperationCompleted(object arg) {
            if ((this.RegistrarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/modificarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void modificarCliente(string nombre, string apellido, string cedula, string direccion, string telefono, int id) {
            this.Invoke("modificarCliente", new object[] {
                        nombre,
                        apellido,
                        cedula,
                        direccion,
                        telefono,
                        id});
        }
        
        /// <remarks/>
        public void modificarClienteAsync(string nombre, string apellido, string cedula, string direccion, string telefono, int id) {
            this.modificarClienteAsync(nombre, apellido, cedula, direccion, telefono, id, null);
        }
        
        /// <remarks/>
        public void modificarClienteAsync(string nombre, string apellido, string cedula, string direccion, string telefono, int id, object userState) {
            if ((this.modificarClienteOperationCompleted == null)) {
                this.modificarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmodificarClienteOperationCompleted);
            }
            this.InvokeAsync("modificarCliente", new object[] {
                        nombre,
                        apellido,
                        cedula,
                        direccion,
                        telefono,
                        id}, this.modificarClienteOperationCompleted, userState);
        }
        
        private void OnmodificarClienteOperationCompleted(object arg) {
            if ((this.modificarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.modificarClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eliminarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void eliminarCliente(int id) {
            this.Invoke("eliminarCliente", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void eliminarClienteAsync(int id) {
            this.eliminarClienteAsync(id, null);
        }
        
        /// <remarks/>
        public void eliminarClienteAsync(int id, object userState) {
            if ((this.eliminarClienteOperationCompleted == null)) {
                this.eliminarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarClienteOperationCompleted);
            }
            this.InvokeAsync("eliminarCliente", new object[] {
                        id}, this.eliminarClienteOperationCompleted, userState);
        }
        
        private void OneliminarClienteOperationCompleted(object arg) {
            if ((this.eliminarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarClienteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cargarDatosCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet cargarDatosCliente(string ci) {
            object[] results = this.Invoke("cargarDatosCliente", new object[] {
                        ci});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void cargarDatosClienteAsync(string ci) {
            this.cargarDatosClienteAsync(ci, null);
        }
        
        /// <remarks/>
        public void cargarDatosClienteAsync(string ci, object userState) {
            if ((this.cargarDatosClienteOperationCompleted == null)) {
                this.cargarDatosClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OncargarDatosClienteOperationCompleted);
            }
            this.InvokeAsync("cargarDatosCliente", new object[] {
                        ci}, this.cargarDatosClienteOperationCompleted, userState);
        }
        
        private void OncargarDatosClienteOperationCompleted(object arg) {
            if ((this.cargarDatosClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cargarDatosClienteCompleted(this, new cargarDatosClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void IngresarCompletedEventHandler(object sender, IngresarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IngresarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IngresarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void registrarProductoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void modificarProductoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void cargarDatosProductoCompletedEventHandler(object sender, cargarDatosProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cargarDatosProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cargarDatosProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void eliminarProductoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void registrarCategoriaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void actualizarCategoriaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void eliminarCategoriaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void cargarDatosCategoriaCompletedEventHandler(object sender, cargarDatosCategoriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cargarDatosCategoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cargarDatosCategoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void registrarProveedorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void actualizarProveedorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void cargarDatosProveedorCompletedEventHandler(object sender, cargarDatosProveedorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cargarDatosProveedorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cargarDatosProveedorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void eliminarProveedorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void registrarVentaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void eliminarventaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void verVentaCompletedEventHandler(object sender, verVentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verVentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verVentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AumentarProductoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RestarProductoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void registrarCompraCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void verCompraCompletedEventHandler(object sender, verCompraCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verCompraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verCompraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void eliminarCompraCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RegistrarUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void actualizarClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void eliminarUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void cargarDatosUsuarioCompletedEventHandler(object sender, cargarDatosUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cargarDatosUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cargarDatosUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RegistrarClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void modificarClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void eliminarClienteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void cargarDatosClienteCompletedEventHandler(object sender, cargarDatosClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cargarDatosClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cargarDatosClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591